### ISSUE TITLE
Pack native dlls for win-x86, win-x64, win-arm64, linux-x86, linux-x64, linux-arm, linux-arm64, osx-x64, osx-arm64, etc.

### ISSUE THREAD

**Issue by AraHaan** [StoneStepsInc/zlib-nuget#1]
I would like it if the native dlls for the above OS's and cpu bitness's can be packed into nuget packages for usage in .NET Managed code that P/Invokes the zlib library and requires at least zlib 1.2.11 (or newer). This would also need to include musl and rhel as well as .NET supports those as well. Thanks for your understanding and hopefully a metapackage can be made that includes the packages for those specific targets as well because I have need for them so my crossplatform code runs everywhere .NET supports.

Why not use System.IO.Compression.Native? This is because it does not export symbols I need that the zlib library does and I can only trust the library that comes from nuget packages as it will for sure be at least the minimum supported version my code needs to work.

Thanks for your understanding.

**Comment by StoneStepsInc** [comment]
This repository wraps the native zLib library in a Nuget package for MSVC projects, without changing the interface or data structure representation. You are looking for a completely different product, which will translate zLib constructs, such as streams, files, memory blocks, etc, into equivalent constructs usable by .Net Core applications. 

In fact, `System.IO.Compression` implements some of these constructs. If you need a more elaborate interface, you will need to find a package that works for you or roll your own. In the latter case, it would be a fairly significant development, mind you.

I will close this issue because this repository is not intended to produce a Nuget package for .Net Core applications.
